<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Product>Lark</Product>
    <Authors>Kingcean Tuan</Authors>
    <Company>ByteDance</Company>
    <Version>0.0.1</Version>
    <AssemblyVersion>0.0.1.0</AssemblyVersion>
    <FileVersion>0.0.1.0</FileVersion>
    <Copyright>Copyright (c) 2026 ByteDance.</Copyright>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/kingcean/larksuite</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <LangVersion>13.0</LangVersion>
    <SignAssembly>True</SignAssembly>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="README.md" />
    <None Include="..\LICENSE" Pack="true" PackagePath="LICENSE" />
  </ItemGroup>
</Project>